import { DAYS, MEALS, assets } from "../../../assets/assets";

export default function PrintableMenu({ weeklyMenu, hostelName, hostelEmail }) {
  if (!weeklyMenu) return null;

  const siteUrl = import.meta.env.VITE_CLIENT_URL;

  return (
    <div className="hidden print:block p-4 bg-white text-gray-900 font-sans text-[11px] leading-tight max-w-200 mx-auto border border-gray-300">
      
      {/* ============================================================
          1. HEADER REGION
          ============================================================ */}
      <div className="relative flex items-center justify-between pb-3 mb-2">
        {/* Dynamic Logo Extraction from your unified assets module */}
        <div className="w-16 h-16 flex items-center justify-center shrink-0">
          <img 
            src={assets.nitkkrLogo || "/logo.png"} 
            alt="NIT Kurukshetra Logo" 
            className="h-full w-full object-contain"
            onError={(e) => {
              e.target.src = "/logo.png";
            }}
          />
        </div>

        {/* Center Headings Space */}
        <div className="text-center flex-1 pr-16">
          <h1 className="text-xl font-black uppercase tracking-tight text-gray-900">
            {hostelName.toUpperCase()}
          </h1>
          <p className="text-sm font-bold text-gray-700 tracking-wide uppercase mt-0.5">
            NIT KURUKSHETRA
          </p>
          <p className="text-[9px] text-gray-400 font-mono mt-1">
            Generated by MessMate on {new Date().toLocaleDateString('en-GB')}
          </p>
        </div>
      </div>

      {/* ============================================================
          2. UNDERLINED TITLE SECTION
          ============================================================ */}
      <div className="text-center py-2 my-2">
        <h2 className="text-base font-black uppercase tracking-widest text-gray-950 underline underline-offset-4 decoration-2">
          MESS WEEKLY MENU SCHEDULE
        </h2>
      </div>

      {/* ============================================================
          3. SCHEDULING MATRIX TABLE
          ============================================================ */}
      <table className="w-full border-collapse border-2 border-gray-800 text-[10.5px]">
        <thead>
          <tr className="bg-gray-50 text-center font-bold border-b-2 border-gray-800 text-gray-900">
            <th className="border border-gray-800 py-2.5 px-1 w-[12%] uppercase font-black text-xs">Day</th>
            <th className="border border-gray-800 py-2 px-2 w-[29%] text-xs font-black">
              Breakfast 
              <span className="block text-[9.5px] font-normal text-gray-500 mt-0.5">(07:30 AM - 09:30 AM)</span>
            </th>
            <th className="border border-gray-800 py-2 px-2 w-[29%] text-xs font-black">
              Lunch 
              <span className="block text-[9.5px] font-normal text-gray-500 mt-0.5">(12:30 PM - 02:30 PM)</span>
            </th>
            <th className="border border-gray-800 py-2 px-2 w-[29%] text-xs font-black">
              Dinner 
              <span className="block text-[9.5px] font-normal text-gray-500 mt-0.5">(07:30 PM - 09:30 PM)</span>
            </th>
          </tr>
        </thead>
        <tbody>
          {DAYS.map((day) => (
            <tr key={day} className="border-b border-gray-800">
              
              {/* Day Labels Column */}
              <td className="border border-gray-800 font-black p-2.5 capitalize text-center align-middle text-gray-900 bg-gray-50/30 text-xs">
                {day}
              </td>

              {/* Meals Loop mapping columns */}
              {MEALS.map((meal) => {
                const data = weeklyMenu[day]?.[meal];
                return (
                  <td key={meal} className="border border-gray-800 p-2.5 align-middle text-center font-medium text-gray-800 leading-normal">
                    
                    {/* Primary Diet Display */}
                    {data?.diet?.length > 0 ? (
                      <span className="text-gray-900 font-semibold text-[11px]">
                        {data.diet.map(item => item.name).join(", ")}
                      </span>
                    ) : (
                      <span className="text-[10px] italic text-gray-400">Not Set</span>
                    )}

                    {/* Extras Highlight Section (Bolded / Red Text Flagging) */}
                    {data?.extras?.length > 0 && (
                      <div className="mt-1.5 pt-1 border-t border-dotted border-gray-300 text-[9.5px] text-red-600 font-black tracking-wide">
                        Add-ons: {data.extras.map(e => `${e.name} (₹${e.price})`).join(", ")}
                      </div>
                    )}

                  </td>
                );
              })}

            </tr>
          ))}
        </tbody>
      </table>

      {/* ============================================================
          4. CUSTOM SPECIFIED INSIGHT BULLETS
          ============================================================ */}
      <div className="mt-5 px-2 space-y-1.5 font-bold text-gray-700 text-[10px] tracking-tight">
        <p className="flex items-start gap-2">
          <span className="text-red-600 font-black text-xs leading-none">➢</span> 
          <span><span className="text-red-600 font-black">Red colored / bold items</span> highlight extra options and will be charged accordingly to your balance ledger.</span>
        </p>
        <p className="flex items-start gap-2">
          <span className="text-gray-900 font-black text-xs leading-none">➢</span> 
          <span>Please check for any dynamic overrides or structural changes to today's menu directly in your live <span className="text-gray-900 font-extrabold">MessMate profile</span>.</span>
        </p>
        <p className="flex items-start gap-2">
          <span className="text-green-700 font-black text-xs leading-none">➢</span> 
          <span>Please rate items on <span className="text-green-700 font-extrabold font-mono underline select-all">{siteUrl}</span> for further improvements and culinary operational enhancements.</span>
        </p>
      </div>

      {/* ============================================================
          5. BOTTOM RIGHT SIGNATURE AUTHORITY
          ============================================================ */}
      <div className="mt-10 pr-4 text-right">
        <div className="inline-block text-center border-t border-gray-200 pt-1.5 min-w-50">
          <p className="font-black text-gray-900 text-xs tracking-wide">
            Mess Committee
          </p>
          <p className="text-[10px] font-bold text-gray-600 mt-0.5 capitalize">
            {hostelName}
          </p>
          <p className="text-[9px] font-medium font-mono text-gray-400 mt-0.5 lowercase">
            {hostelEmail}
          </p>
        </div>
      </div>

    </div>
  );
}