import authApi from './api';
import { protectedApi, publicApi } from './api';

export const verifyWithGoogleAPI = async (credential) => {
  // credential is the ID Token JWT generated by Google
  const response = await authApi.post('/auth/google/verify', { token: credential });
  return response.data;
};

export const registerWithGoogleAPI = async (credentials) => {
  const response = await authApi.post('/auth/google/complete-profile', credentials);
  return response.data;
};

export const loginWithGoogleAPI = async (credential) => {
  const response = await authApi.post('/auth/google/login', { token: credential });
  return response.data;
};

export const fetchHostelsAPI = async () => {
    const response = await publicApi.get('/public/hostels');
    return response.data;
};

export const loginAPI = async (credentials) => {
    const response = await authApi.post('/auth/login', credentials);
    return response.data;
};

export const signupAPI = async (userData) => {
    const response = await publicApi.post('/auth/signup', userData);
    return response.data;
};

export const verifyEmailAPI = async (data) => {
    const response = await authApi.post('/auth/signup/verify',data);
    return response.data;
}

export const resendOtpAPI = async (email) => {
    const response = await protectedApi.post('/auth/resend-otp', { email });
    return response.data;
}

export const sendLoginOtpAPI = async (data) => {
    const response = await protectedApi.post('/auth/login/send-otp', data);
    return response.data;
}

export const loginWithOtpAPI = async (data) => {
    const response = await authApi.post('/auth/login/verify-otp', data);
    return response.data;
}

export const sendForgotPasswordOtpAPI = async (identifier) => {
    const response = await protectedApi.post('/auth/forgot-password/send-otp', { identifier });
    return response.data;
}

export const verifyForgotPasswordOtpAPI = async (data) => {
    const response = await protectedApi.post('/auth/forgot-password/verify-otp', data);
    return response.data;
}

export const resetPasswordAPI = async (data) => {
    const response = await protectedApi.post('/auth/forgot-password/reset', data);
    return response.data;
}

export const changePasswordAPI = async (data) => {
    const response = await authApi.post('/auth/change-password', data);
    return response.data;
}

export const logoutAPI = async () => {
    const response = await authApi.post('/auth/logout');
    return response.data;
};

export const getMeAPI = async () => {
    const response = await protectedApi.get('/auth/me');
    return response.data;
};